# Generated by Django 4.1.4 on 2022-12-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('date_post', models.DateField(verbose_name='date_post')),
                ('actors', models.CharField(max_length=255, verbose_name='actors')),
                ('date_view', models.DateField(verbose_name='date_view')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.category')),
            ],
        ),
    ]
